Решение задач из задания №3 с 1 по 4
js-tasks-ru/jsbasic-20230428_silverhoofche pull request #5
Opened 2023-05-16 13:50 UTC by si1verhoof

2023-05-16 13:51 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-17 06:53 UTC, SinimaWath requested changes

2023-05-17 06:53 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  };
давай вместо этого цикла используем `.map()`

2023-05-17 07:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-17 13:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-18 18:50 UTC, SinimaWath approved these changes

2023-05-18 18:51 UTC, merged